name = "sistem-absensi-kantor-qr"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "absensi_db"
database_name = "absensi-db"
database_id = "28f9f916-2952-4633-b35a-b2edb8be9008"

# Pages specific settings
pages_build_output_dir = ".open-next/worker-assets"
assets_dir = ".open-next/static-assets"

# Environment variables
[vars]
NODE_ENV = "production"

# Dev environment overrides
[env.production.vars]
NODE_ENV = "production"
